# Generated by Django 3.1.5 on 2021-01-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210124_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images_url',
        ),
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, default='elephant.jpg', upload_to=''),
        ),
    ]
